name: Daily GitHub Top 500 Update

on:
  schedule:
    # 08:00 AM India time
    # GitHub Actions uses UTC
    - cron: "30 2 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:

  update-excel:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests openpyxl

      - name: Run GitHub ranking update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python github_ranker.py

      - name: Commit updated Excel
        run: |

          git config user.name "github-actions[bot]"

          git config user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"

          git add github_top_repos_by_interval.xlsx

          git diff --cached --quiet || \
            git commit -m "Daily GitHub Top 500 update"

          git push
